apiVersion: v1
kind: List
items:

 - kind: PersistentVolumeClaim
   metadata:
     name: patchwork-postgresql
     labels:
       patchwork: database
   spec:
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: 1Gi
